import requests
import json

try:
    response = requests.post(
        url="https://openrouter.ai/api/v1/chat/completions",
        headers={
            "Authorization": "Bearer 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",
            "Content-Type": "application/json",
        },
        data=json.dumps({
            "model": "deepseek/deepseek-chat-v3-0324:free",
            "messages": [
                {
                    "role": "user",
                    "content": (
                        "Por favor, responde con un JSON que tenga la siguiente estructura y llena los campos con la información correspondiente:\n"
                        "{\n"
                        "    \"antecedentes_personales\": {\n"
                        "        \"edad\": {},\n"
                        "        \"sexo\": \"\",\n"
                        "        \"peso\": null,\n"
                        "        \"talla\": null,\n"
                        "        \"preferencia\": null,\n"
                        "        \"índice_tabáquico\": {\n"
                        "            \"fuma\": \"\",\n"
                        "            \"observaciones\": []\n"
                        "        },\n"
                        "        \"alcohol\": \"\",\n"
                        "        \"drogas\": \"\",\n"
                        "        \"comorbilidades\": {\n"
                        "            \"sin_fecha\": [],\n"
                        "            \"xxxx\": \"\"\n"
                        "        },\n"
                        "        \"antecedentes_ginecológicos\": {\n"
                        "            \"fum\": {},\n"
                        "            \"menarca\": {},\n"
                        "            \"trh\": \"\",\n"
                        "            \"aco\": \"\",\n"
                        "            \"mpf\": null,\n"
                        "            \"estado_hormonal\": \"\",\n"
                        "            \"métodos_anticonceptivos\": null,\n"
                        "            \"g\": 0,\n"
                        "            \"p\": 0,\n"
                        "            \"c\": 0,\n"
                        "            \"a\": 0\n"
                        "        }\n"
                        "    },\n"
                        "    \"antecedentes_familiares\": {\n"
                        "        \"ascendencia\": [],\n"
                        "        \"lateralidad\": [],\n"
                        "        \"descendencia\": []\n"
                        "    },\n"
                        "    \"estadía_tumoral\": {\n"
                        "        \"mama_izquierda\": {\n"
                        "            \"ultrasonido\": null,\n"
                        "            \"mastografía\": null,\n"
                        "            \"centros_tumorales\": null,\n"
                        "            \"nódulos\": null,\n"
                        "            \"metástasis\": null\n"
                        "        },\n"
                        "        \"mama_derecha\": {\n"
                        "            \"ultrasonido\": null,\n"
                        "            \"mastografía\": null,\n"
                        "            \"centros_tumorales\": null,\n"
                        "            \"nódulos\": null,\n"
                        "            \"metástasis\": null\n"
                        "        }\n"
                        "    },\n"
                        "    \"inmunohistoquímica_tumoral\": {\n"
                        "        \"mama_izquierda\": {\n"
                        "            \"re\": null,\n"
                        "            \"rp\": null,\n"
                        "            \"her2\": null,\n"
                        "            \"ki67\": null,\n"
                        "            \"gh\": null\n"
                        "        },\n"
                        "        \"mama_derecha\": {\n"
                        "            \"re\": null,\n"
                        "            \"rp\": null,\n"
                        "            \"her2\": null,\n"
                        "            \"ki67\": null,\n"
                        "            \"gh\": null\n"
                        "        }\n"
                        "    },\n"
                        "    \"tipo\": {\n"
                        "        \"mama_izquierda\": {\n"
                        "            \"clasificación\": null,\n"
                        "            \"descripcion\": null\n"
                        "        },\n"
                        "        \"mama_derecha\": {\n"
                        "            \"clasificación\": null,\n"
                        "            \"descripcion\": null\n"
                        "        }\n"
                        "    }\n"
                        "}\n"
                        "Considera que la informacion de centros tumorales, \n"
                        "nódulos, metástasis vienen en el diagnóstico,en la extensión tumroal, o en la biología tumoral y que \n" 
                        "se puede representar como t1c o como t3 o ct3 o n0 o m0, entre otras combinaciones pero nosotros solo requeremos la parte de t,n,m. Ademas, las comorbilidades \n"
                        "podrias separarlas por la fecha que indican. y para que tengas mas contexto, el g, p, c, a indican las \n"
                        "gestaciones, los partos, las cesáreas y los abortos. el aco indica Anticonceptivos Orales. \n" 
                        "La mama afectada aparece en el diagnóstico, en la extensión tumoral o en la biología tumoral. pero en caso que no se encuentre ahi\n"
                        "se puede encontrar la mama afectada en otras lineas como de cirugias tal vez, puedes poner la informacion de mama izquierda o mama derecha o ambas en caso de el cancer bilateral. \n"
                        "los antecedentes familiares oheredofamiliares considera laterales como tios, primos o hermanos; la ascendencia son padres, abuelos; la descendencia son hijos\n"
                        "Ahora por favor rellena el diccionario: \n"
                        "gacmc / 84959 / 67 años / dra. martínez\n"
                        "diagnóstico: cdi de mama derecha ec ia triple negativo\n"
                        "comorbilidades:\n"
                        "1. linfoma de hodgkin (1975): 3 ciclos qt (ciclofosfamida, vincristina y otro fármaco) + rt por encima del diafragma (imss)\n"
                        "2. cáncer papilar de tiroides (1988): tiroidectomía + iodo 131 t4/t3\n"
                        "3. cistoadenoma seroso microquístico de páncreas (2016)\n"
                        "4. cdi de mama izquierda ec ia (t1c, n0, m0), re+, her2 -: cc + gc + rt + ia x 5 años (2016)\n"
                        "originaria y residente: guanajuato y ciudad de méxico\n"
                        "ocupación: directora de planeación conalep\n"
                        "seguridad social: issste\n"
                        "tabaco: negado\n"
                        "alcohol: ocasional\n"
                        "drogas: negado\n"
                        "ahf oncológicos: tía materna falleció por cáncer de mama / prima materna con cáncer de mama (desconoce edad al diagnóstico)\n"
                        "menarca 15 años / fum 21 años\n"
                        "g0 p0 c0 a0\n"
                        "trh: durante 30 años\n"
                        "estado hormonal: postmenopáusica\n"
                        "cirugías: esplenectomía abierta (1976) / tiroidectomía (1988) / pancreatectomia distal + resección de implante gástrico + biopsia en cuña de segmento ii hepático + colecistectomía y maniobra de kocher extendida (2016) / cc + gc (2017)\n"
                        "25.08.17 mmg birads 3\n"
                        "22.02.18 mmg birads 3\n"
                        "20.09.18 mmg/us birads 3\n"
                        "14.03.19 mmg/us birads 3\n"
                        "18.09.19 mmg/us birads 2\n"
                        "17.03.20 mmg birads 2\n"
                        "02.03.21 mmg birads 2\n"
                        "09.03.22 mmg birads 2\n"
                        "22.03.23 mmg/us en mama derecha asimetría focal con distorsión en la arquitectura cse tercio medio. en mama izquierda distorsión arquitectura cse tercio medio topografía quirúrgica. calcificaciones redondas benignas. no hay ganglios anormales en axilas. al ultrasonido en mama derecha nódulo espiculado hipoecoico con vascularidad central y periférica en el eje de las 10 de 0.5 cm. no hay alteraciones ductales. birads 5\n"
                        "24.03.23 biopsia de mama derecha: cdi g2 (3+2+1),nlv-, ipn-. ihq re 0%, rp 0%, her2 -, ki67 10%.\n"
                        "oq eangqo (mama derecha sin lesiones palpables. no se palpan adenopatías axilares, claviculares ni cervicales ipsilaterales. mama izquierda sin lesiones palpables. no se palpan adenopatías axilares, claviculares ni cervicales ipsilaterales.\n"
                        "olea ngo revisión de estudios de imagen\n"
                        "revisión de patología\n"
                        "o/'qangos n0 hay dgt\n"
                        "plan: cc + gc + valoración por oncogenética\n"
                        "extensión del tumor: cdi de mama derecha ec ia ct1a-—0.5 cm cn0\n"
                        "biología tumoral: triple negativo re 0%, rp 0%, her2 -, ki67 10%\n"
                        "estado hormonal: postmenopáusica\n"
                        "ecog 0\n"
                        "n0 hay dgt\n"
                        "candidates for preo;\n"
                        "+ patients with inoperablo breast cancer;\n"
                        "»ibc\n"
                        "» bulky or matted cn2 axillary nodos\n"
                        "» cn3 nodal diseaso\n"
                        "» et4 tumors\n"
                        "pn0 ——»no adjuvant thorapy9%\n"
                        "tumor 50.5 cm di\n"
                        "pn1mi —» consider adjuvant chomotherapy*<<*%.1\n"
                        "|pt1, pt2, or pt3; and pn0 or pn1mi (2 illary nodo í 61,0 cm ———+ a hn econ\n"
                        "a bm vi operaba entes! canos pr es im axilar n fumor 0.6-1.0 cm consider adjuvant chomotherapy*:\n"
                        "» prooperativo systomic therapy is preferred for:\n"
                        "o her2-positivo diseaso and tnbc, if 2ct2 or 2cn1\n"
                        "2 largo primary tumor relativo to breast sizo in a patient who * ductalnst\" tumor >1 cm ——————+ adjuvant chemothorapy*<<m (category 1)\n"
                        "¡st conservation * lobular\n"
                        "likely to become cn0 with prooperative systemic 1 error pllary\n"
                        "» prooperativo systemlc therapy can be considered for ct1c, n0 y * metapjastic”\n"
                        "her2-positive disease and tnbc\n"
                        "+ patients in whom definkive surgery may be detayed: i pn+ (21 ipsilatoral motastasos >2 mm) ————————_» adjuvant chemothorapy2s/1 (catogory 1)\n"
                        "5000909909006 9o900b609oanaos o voononronósvoconanovo.\n"
                        "os in tia n0 samples os in tino samples 08 in t1c n0 samples\n"
                        "1.001 1001 1.001\n"
                        "075: a pl\n"
                        "4 ¿ la\n"
                        "e bos0| oso\n"
                        "3 3 |\n"
                        "i e |\n"
                        "025: 0251 02\n"
                        "000: 00 0001\n"
                        "'o 15 o 5 1 15 o 5 10 15\n"
                        "o7/aramo ó rmerrean * time (year) time (year)\n"
                        "strata\n"
                        "e” postop adjurant.ctx+no\n"
                        "strata\n"
                        "y” postop adjuvant.ctx=ho\n"
                        "pp = 0 2 4 + postop adjuvant.ctx=yos\n"
                        "ds as\n"
                        "strata\n"
                        "=” postop.adjuvant.ctx+no\n"
                        "pp = 0 38 == postop adjuvantctx=yes\n"
                        "n0 hay dgt\n"
                        "i re\n"
                        "candidates for preo; pno ——>no adjuvant thorapyw%\n"
                        "+ patients with inoperablo breast cancer; j tumor 50.5 cm e\n"
                        ", bully or matted ch2 axdllary nodes ] pn1mi —» consider adjuvant chomotherapy2<<:%.1\n"
                        "/1mi (s2 ¡llary nodo tu 6-1. os\n"
                        "nea varís vd operaba! a 1 pa: ten ls amm axillary ne fumor 0.6-1.0 cm 'consider adjuvant chomothorapy”*\n"
                        "» prooperativo systomic therapy is preferred for: a\n"
                        "o her2-positivo diseaso and tnbc, if 2ct2 or 2cn1 i\n"
                        "9 largo primary tumor relativo to breast sizo in a patient who « ductalnsty tumor >1 cm ——————+ adjuvant chemothorapy*<< 1 (catogory 1)\n"
                        "dosiros broast conservation i- jobulkz\n"
                        "0 cn+ disease likely to become cn0 with preoperativo systemic | *\n"
                        "therapy. t : micropapillary\n"
                        "» ñ ystemic therapy can bo considered for ct1c, cn0 1 taplast\n"
                        "disease and tnbc\n"
                        "- patient in whom delnlivo surgery may be delayed. 1] pn+ (21 ipsilatoral motastasos >2 mm) ——————————+ adjuvant chemothorapy*<< ii (catogory 1)\n"
                        "sesso sessp>acoscostdoseossocabboosacocreosocosoacook\n"
                        "os in tia n0 samples. os in tib n0 samples 08 in t1c n0 samples\n"
                        "100: 100 1001\n"
                        "|\n"
                        "076 a” pl\n"
                        "e ¿ i\n"
                        "50.50 deso ¿ 0.50 |\n"
                        "e : po\n"
                        "h $ b|\n"
                        "025 025 0251\n"
                        "00: 0.00 0.0\n"
                        "] 10 15 o 5 10 15 o 5 10 15\n"
                        "ora bn [...] ó rmortesn time (year) time (year)\n"
                        "preoperative s\n"
                        "her?2-positive\n"
                        "strata\n"
                        "me” postop.adjuvant.ctx»no\n"
                        "pp = 0.0077 + postop adjuvant.ctx+=yos\n"
                        "rs imei\n"
                        "strata\n"
                        "+ postop adjuvant.ctx+*no\n"
                        "p = 0 2 4 + postop adjuvant.ctx+-yos\n"
                        "mi es\n"
                        "strata\n"
                        "\"+ postop.adjuvant.ctx»no\n"
                        "p = 0 38 === postop.adjuvantctx=yes \n"
                        "{\n"
                    )
                }
            ],
        })
    )
    
    print(f"Status Code: {response.status_code}")
    
    if response.status_code == 200:
        # Parsear la respuesta JSON
        response_data = response.json()
        # Extraer el contenido del mensaje
        if "choices" in response_data and len(response_data["choices"]) > 0:
            message_content = response_data["choices"][0]["message"]["content"]
            print("Response (JSON):")
            print(message_content)  # La IA debería devolver un JSON estructurado
        else:
            print("No se encontró contenido en la respuesta.")
    else:
        print(f"Error en la respuesta: {response.text}")

except requests.exceptions.RequestException as e:
    print(f"An error occurred: {e}")